# docker-compose up --build
# --build bayrağı ise, her bir servis için Docker imajını yeniden oluşturur. İşte bu komutun ne yaptığına dair detaylı bir açıklama:

version: '3.8'

services:
  web:
    build: .
    ports:
      - "3333:80"
    restart: always
